#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <QuartzCore/QuartzCore.h>
#import <math.h>

@interface TALabWindow:UIWindow @end
@implementation TALabWindow
- (UIView*)hitTest:(CGPoint)p withEvent:(UIEvent*)e{return nil;}
@end

static NSString*const P=@"/var/mobile/TestTaLab.txt";
static TALabWindow*gW=nil;static UIView*gB=nil;static __weak UIWindowScene*gLast=nil;static BOOL gLoop=NO;
static void L(NSString*f,...){va_list a;va_start(a,f);NSString*m=[[NSString alloc]initWithFormat:f arguments:a];va_end(a);FILE*x=fopen(P.UTF8String,"a");if(x){fprintf(x,"[TESTTA-2.0] %s\n",m.UTF8String);fclose(x);}}
static BOOL CP(UIWindowScene*s){if(!s)return NO;NSString*r=s.session.role?:@"";if([r localizedCaseInsensitiveContainsString:@"CarPlay"])return YES;CGSize z=s.screen.bounds.size;return z.width>z.height&&z.width>=300&&z.height<=500;}
static UIWindowScene*Find(void){UIWindowScene*best=nil;CGFloat score=-CGFLOAT_MAX;NSString*bid=nil;for(UIScene*r in UIApplication.sharedApplication.connectedScenes){if(![r isKindOfClass:UIWindowScene.class])continue;UIWindowScene*s=(UIWindowScene*)r;if(!CP(s))continue;CGSize z=s.screen.bounds.size;NSString*pid=s.session.persistentIdentifier?:@"";BOOL dash=[pid containsString:@"DBDashboard-Car"]||[pid containsString:@"DBDashboard"];CGFloat hi=-CGFLOAT_MAX;for(UIWindow*w in s.windows)if(w&&!w.hidden&&w.alpha>.01)hi=MAX(hi,w.windowLevel);if(hi==-CGFLOAT_MAX)hi=-10000;CGFloat q=(dash?1e9:0)+(hi>=UIWindowLevelAlert?1e8:0)+z.width*z.height+hi;BOOL tie=fabs(q-score)<.5&&(!bid||[pid compare:bid]==NSOrderedAscending);if(!best||q>score||tie){best=s;score=q;bid=pid;}}if(best!=gLast){gLast=best;if(best)L(@"SELECTED pid=%@ role=%@ size=%@",best.session.persistentIdentifier,best.session.role,NSStringFromCGSize(best.screen.bounds.size));}return best;}
static UIView*Bubble(CGFloat s){UIView*v=[[UIView alloc]initWithFrame:CGRectMake(8,8,s,s)];v.backgroundColor=UIColor.systemYellowColor;v.layer.cornerRadius=s/2;v.layer.borderWidth=7;v.layer.borderColor=UIColor.systemGreenColor.CGColor;UILabel*l=[[UILabel alloc]initWithFrame:v.bounds];l.text=@"LAB";l.textAlignment=NSTextAlignmentCenter;l.font=[UIFont boldSystemFontOfSize:s*.25];l.textColor=UIColor.blackColor;[v addSubview:l];return v;}
static void Tick(void){UIWindowScene*s=Find();if(!s){dispatch_after(dispatch_time(DISPATCH_TIME_NOW,500*NSEC_PER_MSEC),dispatch_get_main_queue(),^{Tick();});return;}if(!gW||gW.windowScene!=s){gW.hidden=YES;gW.rootViewController=nil;gW=[[TALabWindow alloc]initWithWindowScene:s];gW.backgroundColor=UIColor.clearColor;UIViewController*vc=[UIViewController new];vc.view.backgroundColor=UIColor.clearColor;gW.rootViewController=vc;CGRect b=s.coordinateSpace.bounds;if(CGRectIsEmpty(b))b=s.screen.bounds;CGFloat sz=MAX(84,MIN(112,MAX(b.size.height,1)*.40));gB=Bubble(sz);[vc.view addSubview:gB];L(@"CREATED scene=%@ frame=%@",s.session.persistentIdentifier,NSStringFromCGRect(b));}CGRect b=s.coordinateSpace.bounds;if(CGRectIsEmpty(b))b=s.screen.bounds;gW.frame=b;gW.rootViewController.view.frame=(CGRect){CGPointZero,b.size};CGFloat hi=UIWindowLevelAlert;for(UIWindow*w in s.windows)if(w&&w!=gW)hi=MAX(hi,w.windowLevel);CGFloat target=MAX(UIWindowLevelAlert+100,hi+100);if(fabs(gW.windowLevel-target)>.5){gW.windowLevel=target;L(@"PROMOTED %.1f highest=%.1f",target,hi);}gW.hidden=NO;gW.alpha=1;gB.hidden=NO;gB.alpha=1;gB.layer.zPosition=CGFLOAT_MAX;[gB.superview bringSubviewToFront:gB];dispatch_after(dispatch_time(DISPATCH_TIME_NOW,500*NSEC_PER_MSEC),dispatch_get_main_queue(),^{Tick();});}
%ctor{@autoreleasepool{NSString*b=NSBundle.mainBundle.bundleIdentifier?:@"";L(@"LOAD bundle=%@ process=%@",b,NSProcessInfo.processInfo.processName);if([b isEqualToString:@"com.apple.CarPlayApp"]&&!gLoop){gLoop=YES;dispatch_async(dispatch_get_main_queue(),^{Tick();});}}}
